## need to use cmd docker build -f Dockerfile.dev
    ## the -f is to specify what file to use
FROM node:16-alpine

WORKDIR '/app'

## this straight up takes a snapshot so no update if local changes
COPY package.json .

RUN npm install

## could get away with leaving this out since we copying files with local
## also doesn't hurt to have since will be needed in production
COPY . .

CMD ["npm","run", "start"]


## dont for get -t on build creates a tag
## docker run -it -p 3000:3000 IMAGE_ID
## open up the docker app (since running with WSL). Windows has a special area for docker.
    ## explorer.exe . opens the file explorer of where the special area is at.
    ## run repo here
    ## docker run -it -p 3000:3000 -v /app/node_modules -v $(pwd):/app <container id>
