sudo: required
services: docker

before_install:
  - docker build -t dlyu/front-end -f ./fullProject/front-end/Dockerfile.dev ./fullProject/front-end/

script:
  - docker run -e CI=true dlyu/front-end npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'udemy-docker'
  env: 'Udemydocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-106810214139'
  bucket_path: 'docker'
  on:
    branch: master
