#what version of docker-compose to use
version: '3'
#services says a type of a container
services:
  redis-server:
    image: 'redis'
  node-app:
    #restarts if the specified container ("no", always, on-failure, unless-stopped)
    # to use no have to put it in quotes b/c yml's no has value as false
    restart: always
    build: .
    ports:
      # "-" is defining array in yml
      - '8080:8081'
#before using docker-cli we had to manually set the two services(container) to
#talk to each other

#docker-compose does this for us
